export const ROLES = {
  USER: "USER",
  ADMIN: "ADMIN",
  COUNSELOR: "COUNSELOR",
};

export const ROLE_PERMISSIONS = {
  USER: ["VIEW_CAREERS", "BOOK_SESSION", "CHAT"],
  ADMIN: ["MANAGE_USERS", "MANAGE_CAREERS", "VIEW_REPORTS"],
  COUNSELOR: ["VIEW_SESSIONS", "CHAT_WITH_USERS"],
};